spring.application.name=traffic-backend

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/trafficdb
spring.datasource.username=trafficuser
spring.datasource.password=trafficpass
spring.datasource.driver-class-name=org.postgresql.Driver

# Server Configuration
server.port=8080

# Later I would like to seggregate properties for different environments like dev, qa, PROD
# on scaling to 500 users we can use config server separately to separate the
# configuration for different environments.
